PUMPS = 'pumps'
BATTERY_CHARGING = 'battery_charging'
EXPORTS = 'exports'
IMPORTS = 'imports'
BROWN_COAL = 'brown_coal'
BLACK_COAL = 'black_coal'
BIOMASS = 'biomass'
BIOENERGY_BIOMASS = 'bioenergy_biomass'
BIOENERGY_BIOGAS = 'bioenergy_biogas'
DISTILLATE = 'distillate'
GAS_STEAM = 'gas_steam'
GAS_CCGT = 'gas_ccgt'
GAS_OCGT = 'gas_ocgt'
GAS_RECIP = 'gas_recip'
# deprecate
GAS_LFG = 'gas_lfg' 
GAS_WCMG = 'gas_wcmg'
BATTERY_DISCHARGING = 'battery_discharging'
HYDRO = 'hydro'
WIND = 'wind'
SOLAR = 'solar'
ROOFTOP_SOLAR = 'rooftop_solar'

# Fuel tech default order
DEFAULT_FUEL_TECH_ORDER = [
  ROOFTOP_SOLAR,
  SOLAR,
  WIND,
  HYDRO,
  BATTERY_DISCHARGING,
  GAS_WCMG,
  GAS_LFG,
  GAS_RECIP,
  GAS_OCGT,
  GAS_CCGT,
  GAS_STEAM,
  DISTILLATE,
  BIOENERGY_BIOMASS,
  BIOENERGY_BIOGAS,
  BIOMASS,
  BLACK_COAL,
  BROWN_COAL,
  IMPORTS,
  EXPORTS,
  PUMPS,
  BATTERY_CHARGING
]


# Fuel tech type
LOAD = 'load'
SOURCE = 'source'
FUEL_TECH_CATEGORY = {}
FUEL_TECH_CATEGORY[PUMPS] = LOAD
FUEL_TECH_CATEGORY[BATTERY_CHARGING] = LOAD
FUEL_TECH_CATEGORY[EXPORTS] = LOAD
FUEL_TECH_CATEGORY[IMPORTS] = SOURCE
FUEL_TECH_CATEGORY[BROWN_COAL] = SOURCE
FUEL_TECH_CATEGORY[BLACK_COAL] = SOURCE
FUEL_TECH_CATEGORY[BIOMASS] = SOURCE
FUEL_TECH_CATEGORY[BIOENERGY_BIOGAS] = SOURCE
FUEL_TECH_CATEGORY[BIOENERGY_BIOMASS] = SOURCE
FUEL_TECH_CATEGORY[DISTILLATE] = SOURCE
FUEL_TECH_CATEGORY[GAS_STEAM] = SOURCE
FUEL_TECH_CATEGORY[GAS_CCGT] = SOURCE
FUEL_TECH_CATEGORY[GAS_OCGT] = SOURCE
FUEL_TECH_CATEGORY[GAS_RECIP] = SOURCE
FUEL_TECH_CATEGORY[GAS_LFG] = SOURCE
FUEL_TECH_CATEGORY[GAS_WCMG] = SOURCE
FUEL_TECH_CATEGORY[BATTERY_DISCHARGING] = SOURCE
FUEL_TECH_CATEGORY[HYDRO] = SOURCE
FUEL_TECH_CATEGORY[WIND] = SOURCE
FUEL_TECH_CATEGORY[SOLAR] = SOURCE
FUEL_TECH_CATEGORY[ROOFTOP_SOLAR] = SOURCE

FUEL_TECH_RENEWABLE = {}
FUEL_TECH_RENEWABLE[PUMPS] = False
FUEL_TECH_RENEWABLE[BATTERY_CHARGING] = False
FUEL_TECH_RENEWABLE[EXPORTS] = False
FUEL_TECH_RENEWABLE[IMPORTS] = False
FUEL_TECH_RENEWABLE[BROWN_COAL] = False
FUEL_TECH_RENEWABLE[BLACK_COAL] = False
FUEL_TECH_RENEWABLE[BIOMASS] = True
FUEL_TECH_RENEWABLE[BIOENERGY_BIOGAS] = True
FUEL_TECH_RENEWABLE[BIOENERGY_BIOMASS] = True
FUEL_TECH_RENEWABLE[DISTILLATE] = False
FUEL_TECH_RENEWABLE[GAS_STEAM] = False
FUEL_TECH_RENEWABLE[GAS_CCGT] = False
FUEL_TECH_RENEWABLE[GAS_OCGT] = False
FUEL_TECH_RENEWABLE[GAS_RECIP] = False
FUEL_TECH_RENEWABLE[GAS_LFG] = False
FUEL_TECH_RENEWABLE[GAS_WCMG] = False
FUEL_TECH_RENEWABLE[BATTERY_DISCHARGING] = False
FUEL_TECH_RENEWABLE[HYDRO] = True
FUEL_TECH_RENEWABLE[WIND] = True
FUEL_TECH_RENEWABLE[SOLAR] = True
FUEL_TECH_RENEWABLE[ROOFTOP_SOLAR] = True

# Fuel tech label
FUEL_TECH_LABEL = {}
FUEL_TECH_LABEL[PUMPS] = 'Pumps'
FUEL_TECH_LABEL[BATTERY_CHARGING] = 'Battery (Charging)'
FUEL_TECH_LABEL[EXPORTS] = 'Exports'
FUEL_TECH_LABEL[IMPORTS] = 'Imports'
FUEL_TECH_LABEL[BROWN_COAL] = 'Brown Coal'
FUEL_TECH_LABEL[BLACK_COAL] = 'Black Coal'
FUEL_TECH_LABEL[BIOMASS] = 'Biomass'
FUEL_TECH_LABEL[BIOENERGY_BIOGAS] = 'Bioenergy (Biogas)'
FUEL_TECH_LABEL[BIOENERGY_BIOMASS] = 'Bioenergy (Biomass)'
FUEL_TECH_LABEL[DISTILLATE] = 'Distillate'
FUEL_TECH_LABEL[GAS_STEAM] = 'Gas (Steam)'
FUEL_TECH_LABEL[GAS_CCGT] = 'Gas (CCGT)'
FUEL_TECH_LABEL[GAS_OCGT] = 'Gas (OCGT)'
FUEL_TECH_LABEL[GAS_RECIP] = 'Gas (Reciprocating)'
FUEL_TECH_LABEL[GAS_LFG] = 'Gas (Landfill)'
FUEL_TECH_LABEL[GAS_WCMG] = 'Gas (Waste Coal Mine)'
FUEL_TECH_LABEL[BATTERY_DISCHARGING] = 'Battery (Discharging)'
FUEL_TECH_LABEL[HYDRO] = 'Hydro'
FUEL_TECH_LABEL[WIND] = 'Wind'
FUEL_TECH_LABEL[SOLAR] = 'Solar (Utility)'
FUEL_TECH_LABEL[ROOFTOP_SOLAR] = 'Solar (Rooftop)'
